version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  icube:
    image: cocreate/icube:1.0.1
    ports:
      - "5001:5001"
    volumes:
      - ./config/icube-cybervision-plugin.yml:/plugin/icube-cybervision-plugin.yml:ro
      - ./config/fields.yml:/plugin/fields.yml:ro
      - ./config/settings.json:/tmp/settings.json:rw
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - elk


  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge
